<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRvbd5yk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRvbd5yk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerRvbd5yk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerRvbd5yk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerRvbd5yk\appProdProjectContainer(array(
    'container.build_hash' => 'Rvbd5yk',
    'container.build_id' => '569f5e6b',
    'container.build_time' => 1614629472,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerRvbd5yk');
