version: "3"
services:
    DB:
        image: 'riobueno/prestashop:1.7.4.2'
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=admin
            - TZ=America/Lima
        command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
        ports: 
            - "3306:3306"       
    app:
        image: 'riobueno/php-apache:7.2'
        volumes:
        - ./:/var/www/html
        restart: unless-stopped
        depends_on:
            - DB
        ports: 
        - "8888:80"

#correo: demo@demo.com
#clave: 123456789